kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
  namespace: projectcontour
  name: contour-ipv6
spec:
  runtimeSettings:
    health:
      address: "::"
    metrics:
      address: "::"
    xdsServer:
      address: "::"
    envoy:
      http:
        address: "::"
      https:
        address: "::"
      health:
        address: "::"
      metrics:
        address: "::"