kind: GatewayClass
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: contour
spec:
  controllerName: projectcontour.io/gateway-controller
  parametersRef:
    kind: ContourDeployment
    group: projectcontour.io
    name: contour-ipv6
    namespace: projectcontour
---
kind: ContourDeployment
apiVersion: projectcontour.io/v1alpha1
metadata:
  namespace: projectcontour
  name: contour-ipv6
spec:
  runtimeSettings:
    health:
      address: "::"
    metrics:
      address: "::"
    xdsServer:
      address: "::"
    envoy:
      http:
        address: "::"
      https:
        address: "::"
      health:
        address: "::"
      metrics:
        address: "::"